version: '3.3'

services:
    backend:
        build: ./airquality
        ports:
            - "8080:8080"
        restart: on-failure
    
    web:
        build: ./frontend
        ports:
            - "8000:8081"
        volumes:
            - ./src:/etc/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - backend   